### ISSUE TITLE
Should be `version.revision` instead of `version.patch` in the documentation

### ISSUE THREAD

**Issue by 8Observer8** [erincatto/box2d#1023]
There is a little mistake [in the docs](https://box2d.org/documentation/md_foundation.html#autotoc_md29) in this code example:
```c
b2Version version = b2GetVersion();
printf("Box2D version %d.%d.%d\n", version.major, version.minor, version.patch);
```

It should be `version.revision` instead of `version.patch`: https://github.com/erincatto/box2d/blob/main/src/core.c#L100

```c
b2Version version = b2GetVersion();
printf("Box2D version %d.%d.%d\n", version.major, version.minor, version.revision);
```

**Comment by erincatto** [comment]
Looks like I already fixed this.

**Comment by ivan-enzhaev** [comment]
> Looks like I already fixed this.

The problem is here: https://box2d.org/documentation/md_foundation.html#autotoc_md29

<img width="776" height="197" alt="Image" src="https://github.com/user-attachments/assets/9c0716d9-1db6-4011-b549-34628b6061df" />

**Comment by ivan-enzhaev** [comment]
@erincatto It is not fixed. The problem is in the documentation on the website, not in the source code.

**Comment by erincatto** [comment]
I don't publish updated docs to the website between releases. I fixed it in the source.

https://github.com/erincatto/box2d/blob/main/docs/foundation.md
